name: Run K-Means Clustering Script

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10  # ✅ This is the working version

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Script
      run: |
        python kmeans_clustering.py
